[package]
name = "api"
version = "0.1.0"
edition = "2024"


[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
sea-orm = { version = "1.1.13", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"